# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       libngf-qt

# >> macros
# << macros

Summary:    Qt-based client library for Non-Graphic Feedback daemon
Version:    0.2
Release:    1
Group:      System/Libraries
License:    LGPLv2.1
URL:        https://github.com/nemomobile/libngf-qt
Source0:    %{name}-%{version}.tar.bz2
Source100:  libngf-qt.yaml
Requires:   ngfd
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(QtCore)
BuildRequires:  pkgconfig(QtDBus)
BuildRequires:  pkgconfig(QtDeclarative)
BuildRequires:  doxygen

%description
This package contains the Qt-based client library for accessing
Non-graphic feedback services.


%package devel
Summary:    Development package for Qt-based client library for NGF daemon
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
%{summary}.

%package declarative
Summary:    Declarative plugin for NGF clients
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description declarative
%{summary}.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake 

make %{?jobs:-j%jobs}

# >> build post
make doc
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post


%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%{_libdir}/libngf-qt.so.*
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_libdir}/libngf-qt.so
%{_includedir}/ngf-qt/*.h
%{_includedir}/ngf-qt/NgfClient
%{_libdir}/pkgconfig/ngf-qt.pc
%{_mandir}/man3/Ngf_Client.3.gz
# >> files devel
# << files devel

%files declarative
%defattr(-,root,root,-)
%{_libdir}/qt4/imports/org/nemomobile/ngf/*
# >> files declarative
# << files declarative
